### ISSUE TITLE
Criar uma interface bacana para todos os artigos?

### ISSUE THREAD

**Issue by gutierri** [cerebrobr/artigos#31]
Seria bem bacana ter um site(zinho) bem simples, estilo Medium[1] (ou não) com os artigos. Algo apenas para a leitura, nada de comentários ou algo que polua a visibilidade e atrapalhe a leitura.

GitHub Pages deve fazer esse papel.

O que acham?

[1] http://medium.com

**Comment by rodneidesign** [comment]
@gutierri mas não seria retrabalho levar os artigos para lá? É que vejo o cérebro mais como um repositório de links externos, não sei se entendi bem sua ideia.

**Comment by fdaciuk** [comment]
Concordo com o @rodneidesign.. a ideia do cérebro é ser um repositório mesmo, para centralizar os links. Acho que um site não faria muito sentido. Até porque já tem um minisite de apresentação: http://cerebrobr.github.io/cerebro/

**Comment by gutierri** [comment]
@rodneidesign @fdaciuk Eu penso em centralizar conteúdo.

Da um trabalha levar o conteúdo para uma site. Estou pensando como isso pode ser feito, posso até apresentar uma proposta a respeito.
